// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDPb1IJt3YbzrxlTYJJOAl08Rnxs2MkWGY',
    appId: '1:489282987350:web:f8d30914667fad5231a2f7',
    messagingSenderId: '489282987350',
    projectId: 'project-13352',
    authDomain: 'project-13352.firebaseapp.com',
    storageBucket: 'project-13352.appspot.com',
    measurementId: 'G-MFF9D45199',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAdqpsJEi0tN7RB56U9mkda8lc54dsCMK8',
    appId: '1:489282987350:android:544e9fdbea22f59b31a2f7',
    messagingSenderId: '489282987350',
    projectId: 'project-13352',
    storageBucket: 'project-13352.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC79yj-1ZH4ztw-VCqlRDIUgAHrP1eDv5o',
    appId: '1:489282987350:ios:c44edaafd6f011b731a2f7',
    messagingSenderId: '489282987350',
    projectId: 'project-13352',
    storageBucket: 'project-13352.appspot.com',
    iosBundleId: 'com.example.untitled1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC79yj-1ZH4ztw-VCqlRDIUgAHrP1eDv5o',
    appId: '1:489282987350:ios:d6e3a99d4954c25a31a2f7',
    messagingSenderId: '489282987350',
    projectId: 'project-13352',
    storageBucket: 'project-13352.appspot.com',
    iosBundleId: 'com.example.untitled1.RunnerTests',
  );
}
